name: test and build
run-name: lint check, unit test and build
on:
  push:
    branches:
      - 'main'
jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Run unit test with maven
        run: mvn clean test

  build-and-create-artifact:
    needs: run-unit-test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with maven
        run: mvn -DskipTests -B package --file pom.xml

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: crud.war
          path: ./target/

  codeQL-analysis:
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    strategy:
      fail-fast: true
      matrix:
        language: ['java']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize CodeQl
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2



